# Boilerplate code generated by OVITO Pro 3.6.0
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *

# Data import:
pipeline = import_file('/Users/ivan/Dropbox/Mac/Documents/SpinningClusters/Simulations/Test_2/Results_qA5_dp0.50_dens0.200_eT0.00/TrajLog_qA5_dp0.50_dens0.20_eT0.00_nA10000_rp0.15_ra0.15_ep-10.0_ea20.0_T1.0_10*.xyz', multiple_frames = True)

# Manual modifications of the imported data objects:
def modify_pipeline_input(frame: int, data: DataCollection):
    data.particles_.particle_types_.type_by_id_(1).color = (0.6549019607843137, 0.7607843137254902, 1.0)
    data.particles_.particle_types_.type_by_id_(1).radius = 0.5
    data.particles_.particle_types_.type_by_id_(2).color = (0.8705882352941177, 0.9254901960784314, 1.0)
    data.particles_.particle_types_.type_by_id_(2).radius = 0.15
    data.particles_.particle_types_.type_by_id_(3).color = (0.8705882352941177, 0.9254901960784314, 1.0)
    data.particles_.particle_types_.type_by_id_(3).radius = 0.15
pipeline.modifiers.append(modify_pipeline_input)

# Select type:
pipeline.modifiers.append(SelectTypeModifier(types = {2, 3}))

# Delete selected:
pipeline.modifiers.append(DeleteSelectedModifier())